// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msgs/msgs.proto

package msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Domain               uint32   `protobuf:"varint,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Command              uint32   `protobuf:"varint,2,opt,name=command,proto3" json:"command,omitempty"`
	Checksum             []byte   `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetDomain() uint32 {
	if m != nil {
		return m.Domain
	}
	return 0
}

func (m *Header) GetCommand() uint32 {
	if m != nil {
		return m.Command
	}
	return 0
}

func (m *Header) GetChecksum() []byte {
	if m != nil {
		return m.Checksum
	}
	return nil
}

// messages for discover
type Msg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{1}
}
func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (dst *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(dst, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Msg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Node struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{2}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{3}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (dst *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(dst, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{4}
}
func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (dst *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(dst, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

type Locate struct {
	Locate               *Node    `protobuf:"bytes,1,opt,name=locate,proto3" json:"locate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Locate) Reset()         { *m = Locate{} }
func (m *Locate) String() string { return proto.CompactTextString(m) }
func (*Locate) ProtoMessage()    {}
func (*Locate) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{5}
}
func (m *Locate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Locate.Unmarshal(m, b)
}
func (m *Locate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Locate.Marshal(b, m, deterministic)
}
func (dst *Locate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Locate.Merge(dst, src)
}
func (m *Locate) XXX_Size() int {
	return xxx_messageInfo_Locate.Size(m)
}
func (m *Locate) XXX_DiscardUnknown() {
	xxx_messageInfo_Locate.DiscardUnknown(m)
}

var xxx_messageInfo_Locate proto.InternalMessageInfo

func (m *Locate) GetLocate() *Node {
	if m != nil {
		return m.Locate
	}
	return nil
}

type Neighbors struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Neighbors) Reset()         { *m = Neighbors{} }
func (m *Neighbors) String() string { return proto.CompactTextString(m) }
func (*Neighbors) ProtoMessage()    {}
func (*Neighbors) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{6}
}
func (m *Neighbors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Neighbors.Unmarshal(m, b)
}
func (m *Neighbors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Neighbors.Marshal(b, m, deterministic)
}
func (dst *Neighbors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Neighbors.Merge(dst, src)
}
func (m *Neighbors) XXX_Size() int {
	return xxx_messageInfo_Neighbors.Size(m)
}
func (m *Neighbors) XXX_DiscardUnknown() {
	xxx_messageInfo_Neighbors.DiscardUnknown(m)
}

var xxx_messageInfo_Neighbors proto.InternalMessageInfo

func (m *Neighbors) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// get snapshot chain headers
type Ssheaders struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	HighestHash          []byte   `protobuf:"bytes,2,opt,name=highestHash,proto3" json:"highestHash,omitempty"`
	StoppingHash         []byte   `protobuf:"bytes,3,opt,name=stoppingHash,proto3" json:"stoppingHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ssheaders) Reset()         { *m = Ssheaders{} }
func (m *Ssheaders) String() string { return proto.CompactTextString(m) }
func (*Ssheaders) ProtoMessage()    {}
func (*Ssheaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{7}
}
func (m *Ssheaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ssheaders.Unmarshal(m, b)
}
func (m *Ssheaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ssheaders.Marshal(b, m, deterministic)
}
func (dst *Ssheaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ssheaders.Merge(dst, src)
}
func (m *Ssheaders) XXX_Size() int {
	return xxx_messageInfo_Ssheaders.Size(m)
}
func (m *Ssheaders) XXX_DiscardUnknown() {
	xxx_messageInfo_Ssheaders.DiscardUnknown(m)
}

var xxx_messageInfo_Ssheaders proto.InternalMessageInfo

func (m *Ssheaders) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Ssheaders) GetHighestHash() []byte {
	if m != nil {
		return m.HighestHash
	}
	return nil
}

func (m *Ssheaders) GetStoppingHash() []byte {
	if m != nil {
		return m.StoppingHash
	}
	return nil
}

// get account blockchain headers
type Accheaders struct {
	Account              []byte   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	HighestHash          []byte   `protobuf:"bytes,3,opt,name=highestHash,proto3" json:"highestHash,omitempty"`
	StoppingHash         []byte   `protobuf:"bytes,4,opt,name=stoppingHash,proto3" json:"stoppingHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Accheaders) Reset()         { *m = Accheaders{} }
func (m *Accheaders) String() string { return proto.CompactTextString(m) }
func (*Accheaders) ProtoMessage()    {}
func (*Accheaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{8}
}
func (m *Accheaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accheaders.Unmarshal(m, b)
}
func (m *Accheaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accheaders.Marshal(b, m, deterministic)
}
func (dst *Accheaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accheaders.Merge(dst, src)
}
func (m *Accheaders) XXX_Size() int {
	return xxx_messageInfo_Accheaders.Size(m)
}
func (m *Accheaders) XXX_DiscardUnknown() {
	xxx_messageInfo_Accheaders.DiscardUnknown(m)
}

var xxx_messageInfo_Accheaders proto.InternalMessageInfo

func (m *Accheaders) GetAccount() []byte {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Accheaders) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Accheaders) GetHighestHash() []byte {
	if m != nil {
		return m.HighestHash
	}
	return nil
}

func (m *Accheaders) GetStoppingHash() []byte {
	if m != nil {
		return m.StoppingHash
	}
	return nil
}

// inventory
type Inv struct {
	Count                uint32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Type                 uint32   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Hash                 [][]byte `protobuf:"bytes,3,rep,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inv) Reset()         { *m = Inv{} }
func (m *Inv) String() string { return proto.CompactTextString(m) }
func (*Inv) ProtoMessage()    {}
func (*Inv) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{9}
}
func (m *Inv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inv.Unmarshal(m, b)
}
func (m *Inv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inv.Marshal(b, m, deterministic)
}
func (dst *Inv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inv.Merge(dst, src)
}
func (m *Inv) XXX_Size() int {
	return xxx_messageInfo_Inv.Size(m)
}
func (m *Inv) XXX_DiscardUnknown() {
	xxx_messageInfo_Inv.DiscardUnknown(m)
}

var xxx_messageInfo_Inv proto.InternalMessageInfo

func (m *Inv) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Inv) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Inv) GetHash() [][]byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Getdata struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Getdata) Reset()         { *m = Getdata{} }
func (m *Getdata) String() string { return proto.CompactTextString(m) }
func (*Getdata) ProtoMessage()    {}
func (*Getdata) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{10}
}
func (m *Getdata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Getdata.Unmarshal(m, b)
}
func (m *Getdata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Getdata.Marshal(b, m, deterministic)
}
func (dst *Getdata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Getdata.Merge(dst, src)
}
func (m *Getdata) XXX_Size() int {
	return xxx_messageInfo_Getdata.Size(m)
}
func (m *Getdata) XXX_DiscardUnknown() {
	xxx_messageInfo_Getdata.DiscardUnknown(m)
}

var xxx_messageInfo_Getdata proto.InternalMessageInfo

func (m *Getdata) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Getdata) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

// snapshot data
type Ssblock struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ssblock) Reset()         { *m = Ssblock{} }
func (m *Ssblock) String() string { return proto.CompactTextString(m) }
func (*Ssblock) ProtoMessage()    {}
func (*Ssblock) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{11}
}
func (m *Ssblock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ssblock.Unmarshal(m, b)
}
func (m *Ssblock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ssblock.Marshal(b, m, deterministic)
}
func (dst *Ssblock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ssblock.Merge(dst, src)
}
func (m *Ssblock) XXX_Size() int {
	return xxx_messageInfo_Ssblock.Size(m)
}
func (m *Ssblock) XXX_DiscardUnknown() {
	xxx_messageInfo_Ssblock.DiscardUnknown(m)
}

var xxx_messageInfo_Ssblock proto.InternalMessageInfo

// transaction data
type TX struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TX) Reset()         { *m = TX{} }
func (m *TX) String() string { return proto.CompactTextString(m) }
func (*TX) ProtoMessage()    {}
func (*TX) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{12}
}
func (m *TX) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TX.Unmarshal(m, b)
}
func (m *TX) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TX.Marshal(b, m, deterministic)
}
func (dst *TX) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TX.Merge(dst, src)
}
func (m *TX) XXX_Size() int {
	return xxx_messageInfo_TX.Size(m)
}
func (m *TX) XXX_DiscardUnknown() {
	xxx_messageInfo_TX.DiscardUnknown(m)
}

var xxx_messageInfo_TX proto.InternalMessageInfo

// account block data
type Block struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgs_1d15bc81af60dc8c, []int{13}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Header)(nil), "msgs.Header")
	proto.RegisterType((*Msg)(nil), "msgs.Msg")
	proto.RegisterType((*Node)(nil), "msgs.Node")
	proto.RegisterType((*Ping)(nil), "msgs.Ping")
	proto.RegisterType((*Pong)(nil), "msgs.Pong")
	proto.RegisterType((*Locate)(nil), "msgs.Locate")
	proto.RegisterType((*Neighbors)(nil), "msgs.Neighbors")
	proto.RegisterType((*Ssheaders)(nil), "msgs.Ssheaders")
	proto.RegisterType((*Accheaders)(nil), "msgs.Accheaders")
	proto.RegisterType((*Inv)(nil), "msgs.Inv")
	proto.RegisterType((*Getdata)(nil), "msgs.Getdata")
	proto.RegisterType((*Ssblock)(nil), "msgs.Ssblock")
	proto.RegisterType((*TX)(nil), "msgs.TX")
	proto.RegisterType((*Block)(nil), "msgs.Block")
}

func init() { proto.RegisterFile("msgs/msgs.proto", fileDescriptor_msgs_1d15bc81af60dc8c) }

var fileDescriptor_msgs_1d15bc81af60dc8c = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x51, 0x4b, 0xeb, 0x30,
	0x14, 0xc7, 0xe9, 0xda, 0xb5, 0x77, 0x67, 0x1d, 0x17, 0xc2, 0xe5, 0x52, 0xee, 0x53, 0x09, 0xf7,
	0x61, 0x0f, 0x3a, 0x51, 0x3f, 0x81, 0x8a, 0x38, 0x41, 0x87, 0x64, 0x22, 0xbe, 0x66, 0x69, 0x48,
	0xcb, 0xd6, 0xa4, 0x2c, 0x99, 0xb0, 0x57, 0x3f, 0xb9, 0x24, 0x69, 0x37, 0x27, 0x43, 0x5f, 0x9a,
	0xf3, 0x3f, 0x27, 0xe7, 0xfc, 0xfe, 0x3d, 0x2d, 0xfc, 0xae, 0xb5, 0xd0, 0x67, 0xf6, 0x31, 0x69,
	0xd6, 0xca, 0x28, 0x14, 0xd9, 0x18, 0xbf, 0x40, 0x3c, 0xe5, 0xb4, 0xe0, 0x6b, 0xf4, 0x17, 0xe2,
	0x42, 0xd5, 0xb4, 0x92, 0x59, 0x90, 0x07, 0xe3, 0x11, 0x69, 0x15, 0xca, 0x20, 0x61, 0xaa, 0xae,
	0xa9, 0x2c, 0xb2, 0x9e, 0x2b, 0x74, 0x12, 0xfd, 0x83, 0x5f, 0xac, 0xe4, 0x6c, 0xa9, 0x37, 0x75,
	0x16, 0xe6, 0xc1, 0x38, 0x25, 0x3b, 0x8d, 0x6f, 0x21, 0x7c, 0xd4, 0x02, 0xfd, 0x87, 0xb8, 0x74,
	0xe3, 0xdd, 0xd0, 0xe1, 0x45, 0x3a, 0x71, 0x0e, 0x3c, 0x92, 0xb4, 0x35, 0x8b, 0x68, 0xe8, 0x76,
	0xa5, 0xa8, 0x47, 0xa4, 0xa4, 0x93, 0x38, 0x86, 0x68, 0xa6, 0x0a, 0x6e, 0xcf, 0xa7, 0x4a, 0x0a,
	0x77, 0x2a, 0x29, 0xf0, 0x09, 0xc4, 0x0f, 0x8a, 0x51, 0xc3, 0x11, 0x86, 0x78, 0xe5, 0xa2, 0x96,
	0x00, 0x9e, 0x60, 0xbb, 0x48, 0x5b, 0xc1, 0xa7, 0x30, 0x98, 0xf1, 0x4a, 0x94, 0x0b, 0xb5, 0xd6,
	0x28, 0x87, 0xbe, 0x54, 0x05, 0xd7, 0x59, 0x90, 0x87, 0x5f, 0xee, 0xfb, 0x02, 0x16, 0x30, 0x98,
	0x6b, 0x6f, 0x4d, 0xa3, 0x3f, 0xd0, 0x67, 0x6a, 0x23, 0x8d, 0x1b, 0x1f, 0x11, 0x2f, 0x50, 0x0e,
	0xc3, 0xb2, 0x12, 0x25, 0xd7, 0x66, 0x4a, 0x75, 0xd9, 0xba, 0xfe, 0x9c, 0x42, 0x18, 0x52, 0x6d,
	0x54, 0xd3, 0x54, 0x52, 0xb8, 0x2b, 0x7e, 0x41, 0x07, 0x39, 0xfc, 0x1e, 0x00, 0x5c, 0x31, 0xd6,
	0xa1, 0x32, 0x48, 0x28, 0xdb, 0xc3, 0x52, 0xd2, 0xc9, 0xbd, 0x89, 0xde, 0x37, 0x26, 0xc2, 0x9f,
	0x4d, 0x44, 0x47, 0x4c, 0xdc, 0x40, 0x78, 0x2f, 0xdf, 0x0e, 0xdf, 0x73, 0xd4, 0x21, 0x10, 0x44,
	0x66, 0xdb, 0xf0, 0xf6, 0xcb, 0xbb, 0xd8, 0xe6, 0x4a, 0xcf, 0x0b, 0xc7, 0x29, 0x71, 0x31, 0x3e,
	0x87, 0xe4, 0x8e, 0x9b, 0x82, 0x1a, 0xba, 0x6b, 0x09, 0x8e, 0xb4, 0xf8, 0x3d, 0xf9, 0x96, 0x01,
	0x24, 0x73, 0xbd, 0x58, 0x29, 0xb6, 0xc4, 0x11, 0xf4, 0x9e, 0x5f, 0x71, 0x02, 0xfd, 0x6b, 0x2b,
	0x17, 0xb1, 0xfb, 0x41, 0x2f, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x98, 0x78, 0xb9, 0x87, 0xb3,
	0x02, 0x00, 0x00,
}
