// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Node struct {
	IP                   string   `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	UDP                  uint32   `protobuf:"varint,2,opt,name=UDP,proto3" json:"UDP,omitempty"`
	TCP                  uint32   `protobuf:"varint,3,opt,name=TCP,proto3" json:"TCP,omitempty"`
	Hash                 []byte   `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Time                 uint64   `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_707ab1f9f5cfd9d0, []int{0}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Node) GetUDP() uint32 {
	if m != nil {
		return m.UDP
	}
	return 0
}

func (m *Node) GetTCP() uint32 {
	if m != nil {
		return m.TCP
	}
	return 0
}

func (m *Node) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Node) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Node)(nil), "protos.Node")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_node_707ab1f9f5cfd9d0) }

var fileDescriptor_node_707ab1f9f5cfd9d0 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcb, 0x4f, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0x49, 0x5c, 0x2c, 0x7e,
	0xf9, 0x29, 0xa9, 0x42, 0x7c, 0x5c, 0x4c, 0x9e, 0x01, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41,
	0x4c, 0x9e, 0x01, 0x42, 0x02, 0x5c, 0xcc, 0xa1, 0x2e, 0x01, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xbc,
	0x41, 0x20, 0x26, 0x48, 0x24, 0xc4, 0x39, 0x40, 0x82, 0x19, 0x22, 0x12, 0xe2, 0x1c, 0x20, 0x24,
	0xc4, 0xc5, 0xe2, 0x91, 0x58, 0x9c, 0x21, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x83,
	0xc4, 0x4a, 0x32, 0x73, 0x53, 0x25, 0x58, 0x15, 0x18, 0x35, 0x58, 0x82, 0xc0, 0xec, 0x24, 0x88,
	0x5d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0xed, 0x2e, 0x9d, 0x80, 0x00, 0x00, 0x00,
}
